"""add status and mode column to payment table

Revision ID: 07df08b7d795
Revises: d603349d03b5
Create Date: 2026-01-03 16:49:30.105936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07df08b7d795'
down_revision: Union[str, Sequence[str], None] = 'd603349d03b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_date', sa.DateTime(), nullable=False))
    op.add_column('payment', sa.Column('reference_number', sa.String(length=100), nullable=True))
    op.alter_column('payment', 'payment_mode',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('CASH', 'BANK_TRANSFER', 'CHECK', 'CREDIT_CARD', 'DEBIT_CARD', 'MOBILE_PAYMENT', 'OTHER', name='paymentmode', native_enum=False, length=20),
               existing_nullable=False)
    op.alter_column('payment', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'CANCELLED', name='paymentstatus', native_enum=False, length=20),
               existing_nullable=False)
    op.drop_column('payment', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.alter_column('payment', 'status',
               existing_type=sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'CANCELLED', name='paymentstatus', native_enum=False, length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payment', 'payment_mode',
               existing_type=sa.Enum('CASH', 'BANK_TRANSFER', 'CHECK', 'CREDIT_CARD', 'DEBIT_CARD', 'MOBILE_PAYMENT', 'OTHER', name='paymentmode', native_enum=False, length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('payment', 'reference_number')
    op.drop_column('payment', 'payment_date')
    # ### end Alembic commands ###
