"""add status column to invoice table

Revision ID: d603349d03b5
Revises: e2b2dff3ffa6
Create Date: 2026-01-03 14:20:43.884480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd603349d03b5'
down_revision: Union[str, Sequence[str], None] = 'e2b2dff3ffa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=False)
    op.create_index(op.f('ix_client_phone'), 'client', ['phone'], unique=False)
    op.add_column('invoice', sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'PAID', 'PARTIALLY_PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus', native_enum=False, length=20), nullable=False))
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_column('invoice', 'status')
    op.drop_index(op.f('ix_client_phone'), table_name='client')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    # ### end Alembic commands ###
