"""initial schema

Revision ID: fc8acee66e49
Revises: 
Create Date: 2025-12-01 21:15:20.423037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8acee66e49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('post_addr', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('email_queue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.String(length=150), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_queue_id'), 'email_queue', ['id'], unique=False)
    op.create_table('email_receipt_count',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ref', sa.String(length=240), nullable=False),
    sa.Column('counter', sa.BigInteger(), nullable=False),
    sa.Column('last_received', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('body', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_receipt_count_id'), 'email_receipt_count', ['id'], unique=False)
    op.create_index(op.f('ix_email_receipt_count_ref'), 'email_receipt_count', ['ref'], unique=False)
    op.create_table('expense',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('aproved_by', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('payment_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_id'), 'expense', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('recurrent_bill',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('amount_expected', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_due', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurrent_bill_id'), 'recurrent_bill', ['id'], unique=False)
    op.create_index('recurrent_bill_args_req', 'recurrent_bill', ['id', 'client_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_no', sa.String(length=30), nullable=False),
    sa.Column('purchase_no', sa.Integer(), nullable=True),
    sa.Column('date_value', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_due', sa.DateTime(), nullable=False),
    sa.Column('disc_type', sa.String(length=10), nullable=True),
    sa.Column('disc_value', sa.String(length=10), nullable=True),
    sa.Column('disc_desc', sa.Text(), nullable=True),
    sa.Column('client_type', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('is_dummy', sa.Integer(), nullable=True),
    sa.Column('recurrent_bill_id', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('last_view', sa.DateTime(), nullable=True),
    sa.Column('send_reminders', sa.Boolean(), nullable=True),
    sa.Column('reminder_frequency', sa.Integer(), nullable=True),
    sa.Column('reminder_logs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurrent_bill_id'], ['recurrent_bill.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_id'), 'invoice', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_invoice_no'), 'invoice', ['invoice_no'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_desc', sa.String(length=150), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('payment_desc', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_mode', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('last_view', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_invoice_invoice_no'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index('recurrent_bill_args_req', table_name='recurrent_bill')
    op.drop_index(op.f('ix_recurrent_bill_id'), table_name='recurrent_bill')
    op.drop_table('recurrent_bill')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_expense_id'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('ix_email_receipt_count_ref'), table_name='email_receipt_count')
    op.drop_index(op.f('ix_email_receipt_count_id'), table_name='email_receipt_count')
    op.drop_table('email_receipt_count')
    op.drop_index(op.f('ix_email_queue_id'), table_name='email_queue')
    op.drop_table('email_queue')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
